// <auto-generated />
namespace OTS_MVC_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EmpTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmpTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201610101055481_EmpTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
